In [37]:
import tensorflow as tf

In [45]:
print(tf.version)

<module 'tensorflow.compat.v1.version' from '/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/compat/v1/version/__init__.py'>


# Creating Tensors


In [ ]:
string = tf.Variable('this is a string',tf.string)
number = tf.Variable(321, tf.int16)
floating = tf.Variable(9.32, tf.float64)

# Rank/Degree of Tensors

Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor.

In [ ]:
rank1_tensor = tf.Variable(['test','one','is','donne'], tf.string)
rank2_tensor = tf.Variable([['first','second'],['one','two'],['three','four']], tf.string)

In [ ]:
#determine the rank of a tensor 
tf.rank(rank1_tensor)


<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# Shape of tensr

In [ ]:
rank2_tensor.shape

TensorShape([3, 2])

In [ ]:
rank1_tensor.shape

TensorShape([4])

# Changing Shape

In [31]:
tensor1 = tf.ones([1,2,3])  #tf.ones() creates a shape[1,2,3] tensor full of ones
tensor1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [30]:
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor2

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [47]:
tensor3 = tf.reshape(tensor2, [3,-1])
tensor3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>